name: Python application

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # You can also use 'windows-latest' or 'macos-latest' or 'ubuntu-latest'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (if you have them)
      run: |
        # Example command if you have tests
        pytest

    - name: Deploy (if using Heroku, Docker, etc.)
      run: |
        # Example of deployment (if needed)
        # heroku deploy
